version: '3'
services:
  frontend:
    image: uvishka/watch-ci-frontend:latest
    ports:
      - '5173:5173'
    depends_on:
      - backend

  backend:
    image: uvishka/watch-ci-backend:latest
    ports:
      - '5555:5555'


