version: '3'
services:
  frontend:
    image: uvishka/watch-ci-frontend:latest
    ports:
      - '5173:5173'
    networks:
      - watch
    depends_on:
      - backend

  backend:
    image: uvishka/watch-ci-backend:latest
    ports:
      - '5555:5555'
      - '27017:27017'
    networks:
      - watch

  networks:
    design-flow:
      driver: bridge


